XpoASPNETCoreDemo/DevExpress.Xpo.AspNetCoreDemo/Entities/User.cs
using DevExpress.Xpo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DevExpress.Xpo.Demo.Entities {
    public class User : XPLiteObject {
        Guid oid;
        [Key(true)]
        public Guid Oid {
            get { return oid; }
            set { SetPropertyValue("Oid", ref oid, value); }
        }
        string firstName;
        [Size(100)]
        public string FirstName {
            get { return firstName; }
            set { SetPropertyValue("FirstName", ref firstName, value); }
        }
        string lastName;
        [Size(100)]
        public string LastName {
            get { return lastName; }
            set { SetPropertyValue("LastName", ref lastName, value); }
        }
        string email;
        [Size(256)]
        public string Email {
            get { return email; }
            set { SetPropertyValue("Email", ref email, value); }
        }
        public User(Session session)
            : base(session) {
        }
    }
}

XpoASPNETCoreDemo/DevExpress.Xpo.AspNetCoreDemo/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DevExpress.Xpo.Demo.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Cameron Cashwell Project";
        }
    }
}

XpoASPNETCoreDemo/DevExpress.Xpo.AspNetCoreDemo/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DevExpress.Xpo.Demo.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Please Reach Out!";
        }
    }
}

XpoASPNETCoreDemo/DevExpress.Xpo.AspNetCoreDemo/Pages/Data.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DevExpress.Xpo.Demo.Core;
using DevExpress.Xpo.Demo.Entities;

namespace DevExpress.Xpo.Demo.Pages
{
    public class DataModel : PageModel {
        readonly UnitOfWork uow;
        public DataModel(UnitOfWork uow) {
            this.uow = uow;
        }

        public List<UserModel> Users { get; set; }
        public int TotalCount { get; set; }
        public void OnGet() {
            Users = uow.Query<User>()
                .OrderBy(u => u.LastName)
                .ThenBy(u => u.FirstName)
                .Select(u => new UserModel {
                    Oid = u.Oid,
                    FirstName = u.FirstName,
                    LastName = u.LastName,
                    Email = u.Email
                }).ToList();
            TotalCount = uow.Query<User>().Count();
        }
        [HttpPost]
        public IActionResult OnPostDelete(Guid id) {
            var user = uow.GetObjectByKey<User>(id);
            if(user != null) {
                uow.Delete(user);
                uow.CommitChanges();
            }
            return RedirectToPage();
        }
        [HttpPost]
        public IActionResult OnPostCreate(UserModel model) {
            if(model != null) {
                var newUser = new User(uow) {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Email = model.Email
                };
                uow.CommitChanges();
            }
            return RedirectToPage();
        }
    }
    public class UserModel {
        public Guid Oid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
    }
}

XpoASPNETCoreDemo/DevExpress.Xpo.AspNetCoreDemo/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DevExpress.Xpo.Demo.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

XpoASPNETCoreDemo/DevExpress.Xpo.AspNetCoreDemo/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DevExpress.Xpo.Demo.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

XpoASPNETCoreDemo/DevExpress.Xpo.AspNetCoreDemo/Pages/404.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "404!";
}
<div class="centerIt">
<div class="push"></div>

<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<img src="http://thedevtip.com/notes/wp-content/uploads/2018/06/page-not-found.png">

<div class="push"></div>
        
</div>

XpoASPNETCoreDemo/DevExpress.Xpo.AspNetCoreDemo/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}

<div class="pushIt"></div>

<div class="centerIt">

<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>The best ASP.NET and C# Microsite you'll ever view!</p>

<div class="pushIt"></div>
      
<img src="http://thedevtip.com/notes/wp-content/uploads/2018/04/cartoon-story.png">
<br>

</div>

<div class="pushIt"></div>

XpoASPNETCoreDemo/DevExpress.Xpo.AspNetCoreDemo/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact Today!";
}
<div class="centerIt">
<div class="push"></div>

<h2>@ViewData["Title"]</h2>
<h3>@Model.Message / Connect</h3>

<address>
    <strong>GitHubble:</strong> <a href="#">'<span>[at]</span>bestDeveloperIntheWorld'</a><br/>
    <strong>InstaScam:</strong> <a href="#">'<span>[at]</span>bestDeveloperIntheWorld'</a><br/>
    <strong>Twooter:</strong> <a href="#">'<span>[at]</span>bestDeveloperIntheWorld'</a><br/>
</address>

<center>
<div class="mapouter"><div class="gmap_canvas"><iframe width="400" height="400" id="gmap_canvas" src="https://maps.google.com/maps?q=alexandria, va&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://www.crocothemes.net"></a></div><style>.mapouter{text-align:right;height:400px;width:400px;}.gmap_canvas {overflow:hidden;background:none!important;height:400px;width:400px;}</style></div>
</center>

<address>
    Alexandria<br />
    Old Town, VA 22193 USA<br />
    <abbr title="Phone">Tele:</abbr>
    + 1 (XXX) 555 XXXX
</address>    

<div class="push"></div>
        
</div>

XpoASPNETCoreDemo/DevExpress.Xpo.AspNetCoreDemo/Pages/Data.cshtml
@page
@model DataModel
@{
}

<h2 class="centerIt">CRUD Tool</h2>

<div class="push"></div>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Meta ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>E-mail</th>
            <th>Controls</th>
        </tr>
    </thead>
    <tbody>
    <form method="post" asp-page-handler="create">
        <tr>
            <td>-</td>
            <td><input type="text" name="FirstName" /></td>
            <td><input type="text" name="LastName" /></td>
            <td><input type="text" name="Email" /></td>
            <td><button type="submit" class="btn btn-success" />ADD +</td>
        </tr>
    </form>
    @foreach(var user in @Model.Users){
        <tr>
            <td>@user.Oid</td>
            <td>@user.FirstName</td>
            <td>@user.LastName</td>
            <td>@user.Email</td>
            <td>
                <form method="post">
                    <button type="submit" class="btn btn-danger" asp-page-handler="delete" asp-route-id="@user.Oid">REMOVE -</button>
                </form>
            </td>
        </tr>
    }
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>Lump Sum: @Model.TotalCount</td>
        </tr>
    </tbody>
</table>

<div class="push"></div>

XpoASPNETCoreDemo/DevExpress.Xpo.AspNetCoreDemo/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<div class="push"></div>

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="http://thedevtip.com/notes/wp-content/uploads/2018/02/1.jpg" alt="Great Content" class=".img-responsive" />
            <div class="carousel-caption" role="option">
                <h2>The most viewed website on Earth</h2>
                <p>
                    <a class="btn btn-default" href="./Contact" target="_blank">
                        Click Here to Donate
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="http://thedevtip.com/notes/wp-content/uploads/2017/12/132960-blue-white-gray-circle-tapet-geometry.jpg" alt="Great Content" class=".img-responsive" />
            <div class="carousel-caption" role="option">
                <h2>CRUD Functionality Demo</h2>
                <p>
                    <a class="btn btn-default" href="./Data" target="_blank">
                        Click here to View
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="http://thedevtip.com/notes/wp-content/uploads/2018/05/hologram-office-content-2018.jpg" alt="Great Content" class=".img-responsive" />
            <div class="carousel-caption" role="option">
                <h2>The future is in your Donation</h2>
                <p>
                    <a class="btn btn-default" href="./Contact" target="_blank">
                        Click Here to Donate
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="http://thedevtip.com/notes/wp-content/uploads/2018/05/PI_16.11.09_cybersecurity_Featured.png" alt="Great Content" class=".img-responsive" />
            <div class="carousel-caption" role="option">
                <h2>Very Secure Donation Processes</h2>
                    <a class="btn btn-default" href="./Contact" target="_blank">
                        Click Here to Donate
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-4">

     <img src="http://thedevtip.com/notes/wp-content/uploads/2018/05/Superman-facebook.png" class="avatar">
        
        <h2>Where:</h2>
        <ul>
            <li>The best ASP.NET and C# Microsite in the World</li>
            <li>You are free to Donate if you'd like</li>            
        </ul>
    </div>
    <div class="col-md-4">

     <img src="http://thedevtip.com/notes/wp-content/uploads/2018/05/Superman-facebook.png" class="avatar">
        
        <h2>Who:</h2>
        <ul>
            <li>The best ASP.NET and C# Microsite in the World...</li>
            <li>Please just Donate</li>
        </ul>
    </div>
    <div class="col-md-4">

     <img src="http://thedevtip.com/notes/wp-content/uploads/2018/05/Superman-facebook.png" class="avatar">
                 
        <h2>About:</h2>
        <ul>
            <li>VS 2017 for Mac, 7.4.3 (build 10)</li>
            <li>C#</li>
            <li>ASP.NET</li>  
            <li>HTML/CSS/JS</li>                       
        </ul>
    </div>
</div>

<div class="push"></div>

XpoASPNETCoreDemo/DevExpress.Xpo.AspNetCoreDemo/Pages/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP.NET and C# Microsite</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">| ASP.NET and C# Microsite |</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                    <li><a asp-page="/Data">CRUD Functionality</a></li>
                    <li><a asp-page="/About">About</a></li>
                    <li><a asp-page="/Contact">Subtle Donate CTA</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>Copyright &copy; 2068</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>